const API = 'https://novel-api.nabaikabaiaguo.workers.dev';
const SHELF_KEY = 'novelhub-shelf-v3';
const $ = (s, root = document) => root.querySelector(s);
const app = $('#app');
const state = { home: [], shelf: [], cache: new Map(), hero: 0, timer: null, loadingHome: false };
const unsafe = /\b(18\+|adult|explicit|erotica|hentai|porn|smut|nsfw)\b/i;
const esc = value => String(value ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
function pick(obj, keys, fallback = '') { for (const key of keys) if (obj && obj[key] !== undefined && obj[key] !== null && obj[key] !== '') return obj[key]; return fallback; }
function unwrap(value) { if (!value || typeof value !== 'object' || Array.isArray(value)) return value; for (const key of ['data','result','payload','response']) if (value[key] !== undefined) return unwrap(value[key]); return value; }
function arrayFrom(value) { if (Array.isArray(value)) return value; if (!value || typeof value !== 'object') return []; for (const key of ['items','list','records','novels','books','subjects','content','rows']) if (Array.isArray(value[key])) return value[key]; for (const key of Object.keys(value)) if (Array.isArray(value[key])) return value[key]; return []; }
function normalizeBook(raw = {}) { let genre = pick(raw,['genre','category','genres','type'],'Novel'); if (Array.isArray(genre)) genre = genre[0] || 'Novel'; let tags = pick(raw,['tags','keywords','keyword'],[]); if (!Array.isArray(tags)) tags = String(tags).split(/[,，|]/).map(x=>x.trim()).filter(Boolean); let cover = pick(raw,['cover','coverUrl','cover_url','image','imageUrl','pic','thumb','poster'],''); if (cover && typeof cover === 'object') cover = pick(cover,['url','src','href'],''); return { id:String(pick(raw,['id','novelId','novel_id','bookId','nid'],'')), detailPath:String(pick(raw,['detailPath','detail_path','path','detailUrl'],'')), title:String(pick(raw,['title','name','novelName','bookName'],'Untitled')), author:String(pick(raw,['author','writer','authorName','novelAuthor'],'Unknown author')), summary:String(pick(raw,['summary','description','intro','story','desc'],'No description available.')), cover:String(cover||''), genre:String(genre||'Novel'), tags, score:pick(raw,['score','rating','rate','rank'],''), chapters:pick(raw,['chapters','chapterCount','chapter_count'],'') }; }
function normalizeList(payload) { return arrayFrom(unwrap(payload)).map(normalizeBook).filter(book => !unsafe.test([book.title,book.author,book.summary,book.genre,...book.tags].join(' '))); }
async function api(path) { const response = await fetch(path.startsWith('http') ? path : API + path,{headers:{Accept:'application/json'},cache:'no-store'}); if (!response.ok) throw new Error(`API ${response.status}`); return response.json(); }
const bookKey = book => book.id || book.detailPath || book.title;
function remember(books) { books.forEach(book => state.cache.set(bookKey(book),book)); }
function isSaved(book) { return state.shelf.some(item => bookKey(item) === bookKey(book)); }
function toggleShelf(book) { if (isSaved(book)) { state.shelf=state.shelf.filter(item=>bookKey(item)!==bookKey(book)); toast('Removed from My Shelf'); } else { state.shelf=[book,...state.shelf]; toast('Added to My Shelf'); } localStorage.setItem(SHELF_KEY,JSON.stringify(state.shelf)); }
function poster(book,rank='') { const image=book.cover?`<img src="${esc(book.cover)}" alt="${esc(book.title)}" loading="lazy" onerror="this.style.display='none'">`:'<div class="poster-fallback">🦊</div>'; return `<div class="poster">${image}${rank?`<b class="rank">${esc(rank)}</b>`:''}</div>`; }
function card(book,rank='') { remember([book]); const key=bookKey(book); return `<article class="card"><a class="poster-link" href="#/novel/${encodeURIComponent(key)}">${poster(book,rank)}</a><h3 title="${esc(book.title)}">${esc(book.title)}</h3><small>${esc(book.author)}</small><button type="button" class="shelf-btn ${isSaved(book)?'saved':''}" data-save="${esc(key)}">${isSaved(book)?'✓ On shelf':'+ My Shelf'}</button></article>`; }
function section(label,title,books,ranked=false) { return `<section class="section"><div class="head"><div><div class="eyebrow">${esc(label)}</div><h2>${esc(title)}</h2></div></div><div class="row">${books.length?books.map((book,i)=>card(book,ranked?String(i+1).padStart(2,'0'):'')).join(''):'<div class="empty">No stories available yet.</div>'}</div></section>`; }
function bindCommon() { document.querySelectorAll('[data-save]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();const book=state.cache.get(button.dataset.save);if(!book)return;toggleShelf(book);render();})); }
function shortDescription(text, limit = 150) { const clean = String(text || '').replace(/\s+/g,' ').trim(); if (clean.length <= limit) return clean; const cut = clean.slice(0, limit); const lastSpace = cut.lastIndexOf(' '); return (lastSpace > 80 ? cut.slice(0,lastSpace) : cut).trim() + '…'; }
function hero(book,total) { if(!book) return `<section class="hero empty-hero"><div class="hero-content"><div class="hero-copy"><div class="eyebrow">NOVELHUB · FOXY EDITION</div><h1>DISCOVER YOUR NEXT <i>STORY.</i></h1><p>The catalogue is loading. Search for a title, author or genre.</p><form id="heroSearch" class="hero-search"><input id="heroInput" placeholder="Search novels, authors, genres..."><button type="submit">SEARCH</button></form></div></div></section>`; const max=Math.min(6,total.length); return `<section class="hero"><div class="hero-bg">${book.cover?`<img src="${esc(book.cover)}" alt="">`:''}</div><div class="hero-shade"></div><div class="hero-grid"></div><div class="hero-content"><div class="hero-copy"><div class="eyebrow">FEATURED · ${esc(book.genre||'NOVEL')}</div><h1>${esc(book.title)}</h1><div class="hero-meta"><span>${esc(book.author)}</span>${book.score?`<span>★ ${esc(book.score)}</span>`:''}<span>NOVEL</span></div><p>${esc(shortDescription(book.summary))}</p><div class="hero-actions"><a class="primary" href="#/novel/${encodeURIComponent(bookKey(book))}">READ NOW</a><a class="secondary" href="#/novel/${encodeURIComponent(bookKey(book))}">DETAILS</a></div><form id="heroSearch" class="hero-search"><input id="heroInput" placeholder="Search novels, authors, genres..."><button type="submit">SEARCH</button></form></div><div class="hero-poster">${poster(book)}</div></div><div class="hero-controls"><button type="button" data-hero-prev aria-label="Previous featured novel">‹</button><div class="hero-dots">${total.slice(0,max).map((_,i)=>`<button type="button" class="hero-dot ${i===state.hero?'active':''}" data-hero="${i}" aria-label="Featured ${i+1}"></button>`).join('')}</div><button type="button" data-hero-next aria-label="Next featured novel">›</button></div></section>`; }
function renderHome() { clearInterval(state.timer); const books=state.home,current=books.length?books[state.hero%Math.min(6,books.length)]:null; const genres=[...new Set(books.flatMap(book=>[book.genre,...book.tags]).filter(Boolean))].slice(0,12); app.innerHTML=`<div class="home-page">${hero(current,books)}${section('HOT','Popular stories',books.slice(0,12),true)}${section('DISCOVER','Fresh from the catalogue',books.slice(4,16))}<section class="section"><div class="head"><div><div class="eyebrow">BROWSE</div><h2>Explore genres</h2></div><a href="#/genres">VIEW ALL →</a></div><div class="genre-list">${genres.map(g=>`<a class="genre" href="#/search/${encodeURIComponent(g)}">${esc(g)}</a>`).join('')||'<span class="status">Genres will appear when catalogue data loads.</span>'}</div></section></div>`; bindCommon(); $('#heroSearch')?.addEventListener('submit',e=>{e.preventDefault();go($('#heroInput')?.value||'');}); document.querySelectorAll('[data-hero]').forEach(button=>button.addEventListener('click',()=>{state.hero=Number(button.dataset.hero)||0;renderHome();})); $('[data-hero-prev]')?.addEventListener('click',()=>{const count=Math.min(6,books.length);if(count){state.hero=(state.hero-1+count)%count;renderHome();}}); $('[data-hero-next]')?.addEventListener('click',()=>{const count=Math.min(6,books.length);if(count){state.hero=(state.hero+1)%count;renderHome();}}); if(books.length>1) state.timer=setInterval(()=>{state.hero=(state.hero+1)%Math.min(6,books.length);renderHome();},6000); }
async function loadHome() { if(state.loadingHome)return; state.loadingHome=true; app.innerHTML='<div class="loading-page"><div class="loader"></div><p>LOADING NOVEL HUB...</p></div>'; const paths=['/featured?p=1&l=18','/rankings?rank=1&p=1&l=18','/search?q=popular&p=1&l=18']; const results=await Promise.allSettled(paths.map(api)); const merged=[]; results.forEach(result=>{if(result.status==='fulfilled')merged.push(...normalizeList(result.value));}); const unique=[],seen=new Set(); merged.forEach(book=>{const key=bookKey(book);if(!key||seen.has(key))return;seen.add(key);unique.push(book);}); state.home=unique;state.hero=0;remember(state.home);state.loadingHome=false;renderHome(); }
function go(query) { const value=String(query||'').trim(); if(value) location.hash='#/search/'+encodeURIComponent(value); }
async function searchPage(encoded) { const term=decodeURIComponent(encoded||'').trim(); app.innerHTML=`<div class="page search-page"><div class="head"><div><div class="eyebrow">SEARCH</div><h2>Results for “${esc(term)}”</h2></div></div><form id="searchForm" class="big-search"><input id="searchInput" value="${esc(term)}" placeholder="Search novels, authors or genres..."><button type="submit">SEARCH</button></form><div id="status" class="status">SEARCHING THE CATALOGUE...</div><div id="results" class="grid"></div></div>`; $('#searchForm').addEventListener('submit',e=>{e.preventDefault();go($('#searchInput').value);}); try { const books=normalizeList(await api('/search?q='+encodeURIComponent(term)+'&p=1&l=30'));remember(books);$('#status').textContent=books.length?`${books.length} stories found`:'No matching stories found.';$('#results').innerHTML=books.length?books.map(card).join(''):'<div class="empty">Try another title, author or genre.</div>';bindCommon(); } catch(_) { $('#status').textContent='The catalogue could not be reached right now.';$('#results').innerHTML='<div class="empty">Search is temporarily unavailable. Please try again.</div>'; } }
function genresPage() { const genres=[...new Set(state.home.flatMap(book=>[book.genre,...book.tags]).filter(Boolean))];app.innerHTML=`<div class="page search-page"><div class="head"><div><div class="eyebrow">DISCOVER</div><h2>Choose a genre</h2></div></div><div class="genre-list">${(genres.length?genres:['Fantasy','Adventure','Mystery','Drama','Romance','Science Fiction','History','Comedy']).map(g=>`<a class="genre" href="#/search/${encodeURIComponent(g)}">${esc(g)}</a>`).join('')}</div></div>`; }
function shelfPage() { remember(state.shelf);app.innerHTML=`<div class="page search-page"><div class="head"><div><div class="eyebrow">YOUR LIBRARY</div><h2>My Shelf</h2></div></div><div class="grid">${state.shelf.length?state.shelf.map(card).join(''):'<div class="empty">Your shelf is empty.<br>Add novels from the catalogue.</div>'}</div></div>`;bindCommon(); }
async function novelPage(encoded) { const key=decodeURIComponent(encoded||'');const existing=state.cache.get(key)||state.home.find(book=>bookKey(book)===key)||state.shelf.find(book=>bookKey(book)===key);if(!existing){app.innerHTML='<div class="page detail"><div class="empty">Novel not found.</div></div>';return;}let book=existing;try{let path=book.detailPath;if(path&&path.startsWith(API))path=path.slice(API.length);if(!path)path='/novel/'+encodeURIComponent(book.id);book={...book,...normalizeBook(unwrap(await api(path)))};}catch(_){}remember([book]);app.innerHTML=`<div class="page detail"><a class="back" href="#/">← HOME</a><div class="detail-top"><div>${poster(book)}</div><div><div class="eyebrow">NOVEL</div><h1>${esc(book.title)}</h1><p class="author">${esc(book.author)}</p><p class="summary">${esc(book.summary)}</p><button type="button" class="primary" id="saveBook">${isSaved(book)?'✓ SAVED':'+ ADD TO SHELF'}</button></div></div><div class="chapters"><div class="eyebrow">READ</div><h2>Chapters</h2><div id="chapterList" class="status">LOADING CHAPTERS...</div></div></div>`;$('#saveBook').addEventListener('click',()=>{toggleShelf(book);$('#saveBook').textContent=isSaved(book)?'✓ SAVED':'+ ADD TO SHELF';});try{const chapters=arrayFrom(unwrap(await api('/chapters?id='+encodeURIComponent(book.id)+'&order=asc&p=1&l=100')));$('#chapterList').innerHTML=chapters.length?chapters.map((chapter,i)=>{const cid=pick(chapter,['id','chapterId','chapter_id'],'');const title=pick(chapter,['title','name','chapterName'],'Chapter '+(i+1));return `<a class="chapter" href="#/chapter/${encodeURIComponent(cid)}/${encodeURIComponent(book.title)}"><span>${esc(title)}</span><span>→</span></a>`;}).join(''):'No chapters found.';}catch(_){$('#chapterList').textContent='Chapters could not be loaded.';} }
async function readerPage(encodedId,encodedTitle) { const cid=decodeURIComponent(encodedId||''),title=decodeURIComponent(encodedTitle||'Novel');app.innerHTML=`<div class="reader"><div class="reader-bar"><a href="javascript:history.back()">← BACK</a><span>${esc(title)}</span></div><article id="article"><div class="status">OPENING CHAPTER...</div></article></div>`;try{const data=unwrap(await api('/chapter/'+encodeURIComponent(cid)));const content=String(pick(data,['content','text','body'],'No chapter content available.'));const chapterTitle=String(pick(data,['title','name'],'Chapter'));$('#article').innerHTML='<h1>'+esc(chapterTitle)+'</h1>'+content.split(/\n+/).filter(Boolean).map(p=>'<p>'+esc(p)+'</p>').join('');}catch(_){$('#article').innerHTML='<div class="empty">The chapter could not be loaded.</div>';}}
function toast(message) { const el=$('#toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),1800); }
function render() { const route=location.hash.slice(1)||'/';clearInterval(state.timer);if(route.startsWith('/search/'))return searchPage(route.slice(8));if(route.startsWith('/novel/'))return novelPage(route.slice(7));if(route.startsWith('/chapter/')){const parts=route.split('/');return readerPage(parts[2],parts.slice(3).join('/'));}if(route==='/genres')return genresPage();if(route==='/shelf')return shelfPage();loadHome(); }
function setupNavigation() { $('#navSearch')?.addEventListener('submit',e=>{e.preventDefault();go($('#navSearchInput')?.value||'');});$('#menuBtn')?.addEventListener('click',()=>document.body.classList.toggle('menu-open')); }
try { state.shelf=JSON.parse(localStorage.getItem(SHELF_KEY)||'[]');if(!Array.isArray(state.shelf))state.shelf=[]; } catch(_) { state.shelf=[]; }
setupNavigation();window.addEventListener('hashchange',render);window.addEventListener('DOMContentLoaded',render);
